# Generated by Django 5.0.2 on 2024-02-21 20:25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', blank=True),
        ),
    ]
